version: '3.9'

services:
  mongo:
      image: mongo:6.0
      container_name: tranasctions-mongo
      restart: always
      ports:
        - "27018:27017"
      environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      volumes:
        - mongo_data:/data/db
        - ./mongo-init:/docker-entrypoint-initdb.d

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: transactions-api
    depends_on:
      - mongo
    environment:
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URL: ${GOOGLE_REDIRECT_URL}

      MONGO_URI: ${MONGO_URI}

      CREATE_TRANSACTION_URL: ${CREATE_TRANSACTION_URL}

  tracker:
    build:
      context: .
      dockerfile: tracker/Dockerfile
    container_name: tracker
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/sa-key.json
      BASE_TRANSACTION_URL: ${BASE_TRANSACTION_URL}

  nginx:
    image: nginx:1.25
    container_name: transaction-nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api

volumes:
  mongo_data:
