name: Go CI Pipeline

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Run Tests in Parallel
        run: |
          # 1. Find all directories containing .go files
          #    Exclude 'vendor' and other irrelevant folders
          #    The "grep" and "sed" commands ensure we only get clean paths
          #    "go test" runs for each directory found
          find . -type d -not -path "./.git/*" -not -path "./vendor/*" | while read dir; do
            if ls "$dir"/*.go &> /dev/null; then
              echo "Running tests in: $dir"
              go test -v -race -covermode=atomic -coverprofile=coverage.out $dir -parallel 4
            fi
          done

      - name: Check Code Coverage
        run: |
          go tool cover -func=coverage.out
          coverage=$(go tool cover -func=coverage.out | grep total | awk '{print $3}' | sed 's/\%//')
          if (( $(echo "$coverage < 80" | bc -l) )); then
            echo "Test coverage is too low ($coverage%). Minimum required is 80%."
            exit 1
          fi

      - name: Check Cyclomatic Complexity
        run: |
          go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
          gocyclo -over 15 .
